apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kp-sample
  name: kp-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kp-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kp-sample
    spec:
      containers:
      - image: harbor.kmorinaga.com/kpack/app:latest
        name: app
        resources: {}
status: {}
