apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kp-sample
  name: kp-sample
spec:
  ports:
  - name: 80-3000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: kp-sample
  type: LoadBalancer
status:
  loadBalancer: {}
